#!/bin/bash
VMARGSIN='rel/vm.args.in'
VMARGS='rel/vm.args'
COOKIE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
cp $VMARGSIN $VMARGS
echo "-setcookie $COOKIE" >> $VMARGS 
echo "cookie set to '$COOKIE'"
