---
- stat: path="{{ tts_exec }}"
  register: tts_exec_file

- name: Check for running TTS
  # TODO How to hide the error message, in case no tts is running?
  # It looks very evil, but in fact it is expected
  command: "{{ tts_exec }} pid"
  register: check_result
  ignore_errors: yes
  when: tts_exec_file.stat.exists == True

- name: Stop any running TTS
  command: "{{ tts_exec }} stop"
  when: tts_exec_file.stat.exists == True and check_result.rc == 0

- name: Clone TTS git repo
  git:
    dest: "{{ install_dir }}"
    repo: https://github.com/indigo-dc/tts.git
    version: master

- name: Build TTS
  make:
    # TODO How can ansible know if rebar changed anything?
    chdir: "{{ install_dir }}"
    target: rel

- debug:
    # This was done by 'make rel' in the task abovel
    msg: "Secret cookie changed. Any still-running instance of TTS will be inaccesible through the main binary."

- name: Create configuration directory
  file:
    state: directory
    path: "{{ config_dir }}/{{ item }}"
  with_items:
    - oidc
    - scripts
    - services

- name: Copy configuration files
  template:
      src: "{{ item }}"
      dest: "{{ config_dir }}/{{ item }}"
  with_items:
    - main.conf
    - oidc/google.conf
    - oidc/iam.conf
    - scripts/idh-single-user.py
    - scripts/ssh.py
    - services/ssh.conf

- name: (Re)start TTS
  command: "{{ tts_exec }} start"
