---
- stat: path="{{ ansible_env.HOME }}/indigo-dc/tts/_build/default/rel/tts/bin/tts"
  register: tts_binary

- name: Check for running TTS
  # TODO How to hide the error message, in case no tts is running?
  # It looks very evil, but in fact it is expected
  command: "{{ tts_binary.stat.path }} pid"
  register: check_result
  ignore_errors: yes
  when: tts_binary.stat.exists == True

- name: Stop any running TTS
  command: "{{ tts_binary.stat.path }} stop"
  when: tts_binary.stat.exists == True and check_result.rc == 0

- name: Clone TTS git repo
  git:
    dest: "{{ ansible_env.HOME }}/indigo-dc/tts"
    repo: https://github.com/indigo-dc/tts.git
    version: deployment/ansible

- name: Build TTS
  make:
    # TODO How can ansible know if rebar changed anything?
    chdir: "{{ ansible_env.HOME }}/indigo-dc/tts"
    target: rel

- debug:
    # This was done by 'make rel' in the task above
    msg: "Secret cookie changed. Any still-running instance of TTS will be inaccesible through the main binary."

- name: Create configuration directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.config/tts/{{ item }}"
  with_items:
    - oidc
    - scripts
    - services

- name: Copy configuration files
  template:
      src: "{{ item }}"
      dest: "{{ ansible_env.HOME }}/.config/tts/{{ item }}"
  with_items:
    - main.conf
    - oidc/google.conf
    - oidc/iam.conf
    - scripts/idh-single-user.py
    - scripts/ssh.py
    - services/ssh.conf

- name: (Re)start TTS
  command: ./tts start
  args:
    chdir: "{{ ansible_env.HOME }}/indigo-dc/tts/_build/default/rel/tts/bin/"
