#!/bin/bash
VMARGSIN='config/vm.args.in'
VMARGS='config/vm.args'
COOKIE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 32)
cp $VMARGSIN $VMARGS
echo "-setcookie $COOKIE" >> $VMARGS 
echo "cookie set to '$COOKIE'"
