#!/bin/bash
VMARGSIN='config/vm.args.in'
VMARGS='config/vm.args'
COOKIE=$(tr -dc 'a-zA-Z0-9' </dev/urandom | fold -w 32 | head -n 1)
cp $VMARGSIN $VMARGS
echo "-setcookie $COOKIE" >> $VMARGS 
echo "cookie set to '$COOKIE'"
