---
- name: Setup TTS on all TTS servers
  hosts: tts-server
  remote_user: ansible
  become_user: root
  become: yes
  vars:
    install_dir: "{{ ansible_env.HOME }}/indigo-dc/home"
    config_dir: "{{ ansible_env.HOME }}/.config/tts"
    tts_exec: "{{ install_dir }}/_build/default/rel/tts/bin/tts"

  roles:
    - dependencies
    - role: erlang-std
      when: not ansible_distribution == "CentOS"
    - role: erlang-centos
      when: ansible_distribution == "CentOS"
    - tts
